# -*- coding: utf-8 -*-
"""EMRE_SAKLAKOGLU_MIDTERM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dbaOkMQpdJKQLNlLhb4VUGXUNRWHF2yQ

*Hello*, please change the file name as your name_surname_MIDTERM.ipynb and upload to the folder 'DROP MIDTERMS HERE' on 
Drive.
ex: atay_ilgun_MIDTERM.ipynb

Also, create all TD related tasks on one TD file and upload it.
ex: atay_ilgun_MIDTERM.tox
"""



"""Describe what an algorithm is."""

# An algorithm is a methodical set of steps that can be used to make calculations, resolve problems and reach decisions.

"""Explain in what ways algorithmic design is different than the brute-force regular design approach. [50 words]"""

#We can tell that algorithmic design is the future because different than the regular design approach with the algorithmic design we are creating the machines which creating the design.
#What is the meaning of this? The meaning is until today people tried to create designs but teaching the machines to do that presenting us to unlimited resources.
#Now every people can design with the help of machines and algorithms.

"""In 100 words meditate on how an new approach on design such as one that is algorithmic could affect your work practice."""

#Algorithmic design will affect all the designers because programmers programming machines to design works these days.
#If we create machines which can design anything, we can get unlimited output.
#People are limited creatures and they are not able to do everything that machines can do.
#With the machine learning people started to teach machines how to create, how to design. 
#So, designers started to get afraid of algorithmic design because in the future machines can erase designers.
#For me designers have to improve themselves and they need to understand future started to being build with algorithms.

"""Create a python dictionary for your name surname and year of birth."""

a_dict = {'name':'Emre', 'surname':'Saklakoglu','yearofbirth':'1996'}
#done

"""Write a conditional so If the first letter of your name is 'a' print 'my initial is a!'"""

name='emre'

if name[0] == "e":
  print("e")
  #done

"""Write a conditional so If your surnames letter count is divisable by 3 print 'it is divisible' if not 'not divisible'."""

a_dict['surname']

surname = 'Saklakoglu'

if len(surname) %3:
  print('it is divisible')

"""Change your year of birth to 2678."""

a_dict = {'name':'Emre', 'surname':'Saklakoglu','yearofbirth':'1996'}

a_dict['yearofbirth']

a_dict['yearofbirth']=2678

a_dict['yearofbirth']
#Done

"""TOUCHDESIGNER TIME.

Create a red box [in geo comp] and make it emit particles with a birth rate of 2500.
"""

#Done

"""Import a moving image and a sound file in TD.
Add at least two filters to the image file.
Make 2 parameters of these filters responsive to the audio.
"""

#Done

"""Create a torus and modify its x-size with an LFO with the frequency of 0.75."""

#Done

"""Create a sphere and create an amorph moving shape using 'noise'."""

#Done

"""Create a box and apply an image texture on it."""

#Done